language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alexnight22/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexnight22/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-306554650836"
  bucket_path: "docker"
    on: 
      branch: master
    access_key-id: $AWS_ACCESS_KEY
    secret-access-key: $AWS_SECRET_KEY